repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.1.0
    hooks:
      - id: end-of-file-fixer
      - id: trailing-whitespace
  - repo: https://github.com/psf/black
    rev: 22.1.0
    hooks:
      - id: black
  - repo: https://github.com/pycqa/flake8
    rev: 4.0.0
    hooks:
      - id: flake8
        additional_dependencies:
          - flake8-black>=0.1.1
